steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
      
  - label: ":hammer: IaC"
    command: "iac.sh"
    key: build
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: ":test_tube: Test"
    command: "script.sh"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: "script.sh"
    key: deploy
    depends_on: test

